http:
  port: <%HOST_PORT%>
logger:
  level: <%LOG_LEVEL%>
  metadata:
    service: softAssist
  externalApiLogging: true
  requestLogging: true
  externalApiInteractionOptions:
    json: true
    retry: 2
    verbose_logging: false
    delay: 500
    factor: 2
    accepted: -400
      -404
atlassian:
  user: jmeffert@uncc.edu
  token: ATATT3xFfGF0JCViMFjhXh0d8or5cHv4lj0hXGs7DmaH9b5Lp1cJSTb_FyHjE3zr4g-SCq5I2TsOrBchRPrEb2z9d2kfc6VPmGrjEwtsOU8kHXE_lGs_yHrzrHhKCkFBqZ1LRWyiROv-cM2pldP-ovvkCeka7BIp_297VK8Ww74sAlyk7ueTFEw=06B7D388
  jira:
    url: https://softassist.atlassian.net
MONGO_URI: mongodb+srv://softassist-api:6823PxS7yO9Lj01g@softassist-mongodb-b0219f09.mongo.ondigitalocean.com/admin?tls=true&authSource=admin
WHISPER_API_KEY: 3BzQ0HuBab9A5Mq1ZOcq5cZcdULvaYJd
CLOUDCONVERT_API_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjg4YmFiOWRmOWIwNTUzMjlmOTdhYzMzYzYyN2ZmOWJiNzk5MmI2Y2Y1ZmYzOGQxMjZlMjYzNGFiYmFjY2VhYTM0ZjlmOTQxNTA2ODNkYTYiLCJpYXQiOjE3NDQxNTgwNzAuNDA1NTc1LCJuYmYiOjE3NDQxNTgwNzAuNDA1NTc3LCJleHAiOjQ4OTk4MzE2NzAuNDAwODQ4LCJzdWIiOiI3MTU4Mjk5NCIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.JIrZHGPiwcakX843meqr5DM-rxWgC2-jXWMFcCtCXgsfzGYYwlcSr8ZuEFKEJMs_nIongaTgSuHSNCXpPEQkBVq5ZvbV-m_vfi6I_hTv1Yvb_LhSjlRU-tNK3KKBgjUsOz3_Zugz8ILDH1BiPp5LCRKZZdwlGcI3wYdLr5EBhrhGPlc_n8mTpOJx0KA26Dirdt2H6EhcbMesoZ8FZDVOjJFewYztkHIUeWbG0TztcJb6rPqMC5_0cqCoJdo1YKZyiFpLGjU1QUxeqxFTJyR-ySr9OxYYkP91BronyBsNgu_zsRY1RbIfmQ_SKShKkD7jumHJ20aI06oY3rXiq03WhNn-kdLlncU31GG00FcCYKYkkB8e9eNV3VugaEUP-Z3eCwYjdJ2SXL8tK0BZSDAhDnIeEMqb5t8uJY3kHFbMLKBK4AUnzoBqV0ABbXETooxCMnczs-FEkVna_G8cef4TXLQg69uHxaIQEZo15rRSC3TOsQ9YgXhC8VoZNpOPzAoBgqh9YF0cTKtOuKKLw9RM2MrJMShhxKoLGsyCb2oJq8TOYy16f9q5OYfwriW3sUMgsyw2QxdvJeStz4ulFOfiT1HYxX_D6enSVSd5UzYv5c_TR78wuNWvmwwCsJwQd0LEANoDl6YVR-9ZoKSCx4QXLOzvcrfy4IqfjTm4sV1gWWo
github:
  token: <%GITHUB_TOKEN%>
OPENAI_API_KEY: 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
OPENAI_API_KEY_LANGCHAIN: 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

