http:
  port: <%HOST_PORT%>
logger:
  level: <%LOG_LEVEL%>
  metadata:
    service: softAssist
  externalApiLogging: true
  requestLogging: true
  externalApiInteractionOptions:
    json: true
    retry: 2
    verbose_logging: false
    delay: 500
    factor: 2
    accepted: -400
      -404
atlassian:
  user: jmeffert@uncc.edu
  token: ATATT3xFfGF0_Z7veG9xpzHJn7BphO_ylzPCE6AbJU79wzjHXJfbuqDvXsgvpYmBKkSPIZIi5uUS1-CvKUtFyMsGL555BGXklXkHI2xPUdBUwWbmOofrbpe7Xu2LbzIcjwQ12HPB5ZE3LwOSYjeYeluz86BA1mfXnj4Zw3bi-aIFZU358tViubw=7809F4F6
  jira:
    url: https://softassist.atlassian.net
