http:
  port: <%HOST_PORT%>
logger:
  level: <%LOG_LEVEL%>
  metadata:
    service: softAssist
  externalApiLogging: true
  requestLogging: true
  externalApiInteractionOptions:
    json: true
    retry: 2
    verbose_logging: false
    delay: 500
    factor: 2
    accepted: -400
      -404
atlassian:
  user: jmeffert@uncc.edu
  token: ATATT3xFfGF0_Z7veG9xpzHJn7BphO_ylzPCE6AbJU79wzjHXJfbuqDvXsgvpYmBKkSPIZIi5uUS1-CvKUtFyMsGL555BGXklXkHI2xPUdBUwWbmOofrbpe7Xu2LbzIcjwQ12HPB5ZE3LwOSYjeYeluz86BA1mfXnj4Zw3bi-aIFZU358tViubw=7809F4F6
  jira:
    url: https://softassist.atlassian.net
MONGO_URI: mongodb+srv://softassist-api:6823PxS7yO9Lj01g@softassist-mongodb-b0219f09.mongo.ondigitalocean.com/admin?tls=true&authSource=admin
WHISPER_API_KEY: 3BzQ0HuBab9A5Mq1ZOcq5cZcdULvaYJd
CLOUDCONVERT_API_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjg4YmFiOWRmOWIwNTUzMjlmOTdhYzMzYzYyN2ZmOWJiNzk5MmI2Y2Y1ZmYzOGQxMjZlMjYzNGFiYmFjY2VhYTM0ZjlmOTQxNTA2ODNkYTYiLCJpYXQiOjE3NDQxNTgwNzAuNDA1NTc1LCJuYmYiOjE3NDQxNTgwNzAuNDA1NTc3LCJleHAiOjQ4OTk4MzE2NzAuNDAwODQ4LCJzdWIiOiI3MTU4Mjk5NCIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.JIrZHGPiwcakX843meqr5DM-rxWgC2-jXWMFcCtCXgsfzGYYwlcSr8ZuEFKEJMs_nIongaTgSuHSNCXpPEQkBVq5ZvbV-m_vfi6I_hTv1Yvb_LhSjlRU-tNK3KKBgjUsOz3_Zugz8ILDH1BiPp5LCRKZZdwlGcI3wYdLr5EBhrhGPlc_n8mTpOJx0KA26Dirdt2H6EhcbMesoZ8FZDVOjJFewYztkHIUeWbG0TztcJb6rPqMC5_0cqCoJdo1YKZyiFpLGjU1QUxeqxFTJyR-ySr9OxYYkP91BronyBsNgu_zsRY1RbIfmQ_SKShKkD7jumHJ20aI06oY3rXiq03WhNn-kdLlncU31GG00FcCYKYkkB8e9eNV3VugaEUP-Z3eCwYjdJ2SXL8tK0BZSDAhDnIeEMqb5t8uJY3kHFbMLKBK4AUnzoBqV0ABbXETooxCMnczs-FEkVna_G8cef4TXLQg69uHxaIQEZo15rRSC3TOsQ9YgXhC8VoZNpOPzAoBgqh9YF0cTKtOuKKLw9RM2MrJMShhxKoLGsyCb2oJq8TOYy16f9q5OYfwriW3sUMgsyw2QxdvJeStz4ulFOfiT1HYxX_D6enSVSd5UzYv5c_TR78wuNWvmwwCsJwQd0LEANoDl6YVR-9ZoKSCx4QXLOzvcrfy4IqfjTm4sV1gWWo
OPENAI_API_KEY: ${OPENAI_API_KEY}
